### PR TITLE
Improve render of infested leaves

### PR DESCRIPTION
**Pull request by Tencao**
This should massively improve FPS when faced with alot of infested leaves, such as a forest being fully infested.

### CODE REVIEW

**Comment by Tencao** [comment]
I would like to also state this is not a simple change to FastTESR, this is a complete model change and as such has a lot more FPS gain than FastTESR.

**Comment by SirLyle** [comment]
This doesn't contain my chunk update fix so each leaf block is causing multiple chunk updates per tick. The baked models require the chunk updates to rerender, the chunk updates are slower than FastTESRs.

Compare a video of me testing the [FastTESR](https://gfycat.com/gifs/detail/UnselfishJoyfulBernesemountaindog) (progress changed to match the rate of the model based one) which had faster spreading and higher frames versus this one of the [model based leaves](https://gfycat.com/gifs/detail/CarelessApprehensiveGrizzlybear). Videos have about 40 seconds of the end cut off, basically more of the same.

Baked models are good for things that don't change, like if someone left a bunch of infested leaves sitting around as decoration or something. But during their progression TESRs are better than repeatedly baking each model just because they don't require redrawing the whole chunk. For the usage that infested leaves tend to have (dynamic) reducing chunk redraws is better I think.

That said, perhaps finished infested leaves should convert themselves to a different blockstate which uses a baked fixed model instead of a TESR. Can you bind a model to a single blockstate?

**Comment by Tencao** [comment]
I'll pull your changes later today and merge them with my own, as well as try to swap the baked model to only use the finished state, however there's nothing in that code that calls the block to redraw more than a regular dirt block would, all that's really changing is the color the quads are  being rendered at by minecraft similar to how grass blocks change color based on biome.

**Comment by SirLyle** [comment]
The tileEntity causes the chunk updates in markdirtyclient.

**Comment by Tencao** [comment]
I'll have a look while I port your changes over, see if I can improve it in anyway

**Comment by Tencao** [comment]
I've merged your render changes and I'm in the process of setting up switching of render types once the progress is 100%, as well as remove any uneeded ticking after that, and a few other optimizations that you can freely dismiss if you don't agree with them. I'll try and upload the finished code later tonight for review

**Comment by SirLyle** [comment]
Cool, looking forward to them.

**Comment by Tencao** [comment]
I've ported all my recent changes, including the render split. One bug I haven't been able to track down yet is when converting from infecting to fully infected, there's a brief moment where it goes black before returning to normal, once I track that down the transition should be unnoticeable by players.

**Comment by ghost** [comment]
so is this being added to Ex Nihilo to fix the silkworms cause people r getting annoyed of crashing cause of them

**Comment by Tencao** [comment]
@xKnightGamingx These things need a lot of testing and tweaking to make sure they work properly and don't make any existing issues worse.

**Comment by ghost** [comment]
ok just was asking if there was a quick fix I could do on my config as a temp fix is all

**Comment by Tencao** [comment]
Once I've fixed the weird block shadow bug, I'll build a test jar you can use so you can tell me how well it runs

**Comment by SirLyle** [comment]
@xKnightGamingx 

Tenaco has also merged in the fixes for all Ex Nihilo Tile Entities causing multiple unnecessary chunk updates per tick, once it is tested it will be merged in. It's a substantial rewrite of the rendering/TE syncing/and infested leaves behavior. Not really a quick config fix.

It will address issues #33 and #45 and some underlying code issues.

@Tencao need help tracking down the shadow block bug? I have vacation days I'm burning next week and will have lots of time to look at it.

**Comment by SirLyle** [comment]
It appears the issue is in the color interpolation on the RenderInfestingLeaves TESR for the last tick: change them all to be:

        rColor += round((255 - rColor)*min(1.0f,te.getProgress()));
        gColor += round((255 - gColor)*min(1.0f,te.getProgress()));
        bColor += round((255 - bColor)*min(1.0f,te.getProgress()));

and add

    import static java.lang.Math.min;

to the imports.

**Comment by Tencao** [comment]
I'll do that once I get home and report back

**Comment by SirLyle** [comment]
@Tencao when you get a chance check out the [RenderingAdjustment branch](https://github.com/BloodWorkXGaming/ExNihiloCreatio/tree/RenderingAdjustment) I merged in your changes and adjusted the appearance of the Infesting TESR.

If these are what you are aiming for pull them into your branch so they are included in this PR.

**Comment by Tencao** [comment]
Sorry for the delay, been busy the past few days. I'll have a look at them now

**Comment by Tencao** [comment]
This should be pretty much complete now. For those who want to test for bug reporting, download here - 
https://mega.nz/#!DAB3RSJb!9umYTKWK-pMNLakMTbnOGXtTbkQLXECbaQEqsxWHorc

@SirLyle If you want to review the changes now is the best time. Personally the only thing I really want to change is to get the leaves color a little more closer to the original, but right now it's still fine

**Comment by SirLyle** [comment]
It's performing much better in the flat leaf-world, averaging around 40-100 fps with only occasional drops to < 20 fps. The TESR render range does make it a little weird looking from a far, but I think that is an acceptable compromise that shouldn't cause issues for most players.

Lighting of the TESR is a little weird for interior leaves since the infested leaf blocks block light, we may want to consider making them not block light.

**Comment by Tencao** [comment]
Yeah, I've noticed even a block on its own renders slightly darker than the baked version, not 100% sure why

**Comment by SirLyle** [comment]
One subtle change I made in my branch that improved the color of the TESR was to instead of going towards true white (#FFFFFF) use

```
        final int maxRGB = max(color >> 16 & 0xff, max(color >> 8 & 0xff, color & 0xff));
```

I.e. the max value of the RGB components.

Which gives a grey with a similar brightness as the uncolored leaves. If we instead want the final leaves to be lighter like the TESRs we'll need to apply a white tint on top of the leaves in the baked model.

Not sure if we can use ambient occlusion on a FastTESR but we could try turning it off on the baked model, it'll make it a little brighter around the edges to match the TESR.

**Comment by Tencao** [comment]
I'll have to try your change, but I know that before the end result of the infesting leaves would be far less gray than the fully infested one, making the jump noticeable. As for ambient occlusion, we can give it a go see how it turns out

**Comment by Tencao** [comment]
Just want to say I've also got a few ideas to try when I get home that may or may not help the blocks light issue

**Comment by Tencao** [comment]
So I'm experimenting with dynamic ticking, basically this should make the performance that much better when dealing with lots of infested leaves, as once there's no more leaves around them, they will effectively stop ticking until a block update is called and that block update is a leaf. Additionally, these will tick every 10 ticks instead of every tick, making them far more efficient on the cpu, however default config values will need to be adjusted to compensate.

**Comment by Tencao** [comment]
@SirLyle I tried to add your way of getting color but it always came out gray. If you can implement it into the current code let me know how

**Comment by SirLyle** [comment]
With the latest source I am getting a `java.lang.ClassNotFoundException` crash caused by the Util.getNearbyLeaves function. [Possibly related to this](https://gist.github.com/androidfred/bc64da9e6a355b984d37439ed63ae16b).

I got it working by just passing back a list of block and creating a `infestLeafBlock(World world, BlockPos pos)` function in BlockInfestingLeaves which calls the exisiting infestLeafBlock function after grabbing the state.

I'm thinking it might be worth it to change back to the original TESR (for the infested leaves only) instead of the new FastTESR, so that we have access the the OpenGlHelper, and don't have to do manual face culling. I'm suspecting manually culling faces is more costly than the small overhead from a full TESR versus a FastTESR, it'll also give us access to better lighting control. The baked model and lack of chunk redraws may be the most performance gain we can achieve.

**Comment by Tencao** [comment]
Yeah honestly did not expect that crash, I'll have to rewrite it to remove the pair option, however now that I think about it I can optimize it further as passing the state back is probably unneeded and I can just pass the pos back instead.

**Comment by SirLyle** [comment]
@Tencao There's a Ex Nihilo Creatio discord if you wish to join (https://discord.gg/tJRujAV)

**Comment by SirLyle** [comment]
@Tencao Check out the [RenderingAdjustment branch](https://github.com/BloodWorkXGaming/ExNihiloCreatio/tree/RenderingAdjustment), I've taken your latest code and reverted the TESR to improve appearances, and disabled ambient occlusion on the baked model. The appearance seems good enough to merge.

**Pull request merged**
