### PR TITLE
Add water wheel placement auto orientation.

### PR DESCRIPTION
**Pull request by Codetector1374**
The waterwheel now will look for a water wheel to orientate itself. (Easier placement)

### CODE REVIEW

**Comment by SirLyle** [comment]
Something like this may be better as it includes axles:

        for(EnumFacing face : EnumFacing.HORIZONTALS){
            TileEntity teAdjacent = worldIn.getTileEntity(pos.offset(face));
            // Includes axles and providers
            if((teAdjacent instanceof IRotationalPowerMember) &&
                    !(teAdjacent instanceof IRotationalPowerConsumer)){
                te.facing = face.getOpposite();
            }
        }

**Comment by Codetector1374** [comment]
Yeah, thanks for the advice, will implement it now.

**Comment by Codetector1374** [comment]
Okay, I have made the changes

**Comment by Codetector1374** [comment]
And also gives the player facing priority when multiple power providers are present.

**Pull request merged**
