### PR TITLE
Many Changes

### PR DESCRIPTION
**Pull request by SirLyle**
Addresses:

* Issue #132
* Issue #130
* Issue #123 
  * testing for regressions may be needed.
* Issue #122 
* Issue #120 
* Issue #118 
* Most of Issue #114 
  * Forestry addons still need their hives registered.
* Half of Issue #91 
  * durability is infeasible without breaking the entire sieve system. But combining was added.
* Adds a Tinkers Crook
* Adds a Tinkers Sledge Hammer 
  * disabled if Tinkers' Complement is installed.

### CODE REVIEW

**Comment by CrankySupertoonArchive** [comment]
I approve

**Comment by SirLyle** [comment]
Your bug fix in src/main/java/exnihilocreatio/compatibility/jei/CompatJEI.java may have issues if tconstruct is loaded, but the sledge hammer is disabled.

**Comment by BloodWorkXGaming** [comment]
True, thanks ^^
Not really a bug fix tho :P
Just thought it would be cool to have buuuuut it doesn't work as intended
anyways ^^

SirLyle <notifications@github.com> schrieb am Sa., 20. Okt. 2018, 22:02:

**Comment by SirLyle** [comment]
You could probably grab the default tinkers tools for each material (generated by tconstruct) as itemstacks and register those as catalysts. Might also be possible to make a custom Ingredient that ignores NBT data and will match every sledge hammer.

**Comment by Onigeshi** [comment]
is this gonna make it in a update soon? like I see the artificial hives and a lot of stuff.. i've seen this 2-3 weeks ago and waited since :(

**Comment by BloodWorkXGaming** [comment]
Sorry, I am currently swamped with university and life, so don't have much
time to work on mods.... :/

DrakusorU <notifications@github.com> schrieb am So., 18. Nov. 2018, 17:48:

**Pull request merged**
